"""add_unique_constraint_to_task_completions

Revision ID: a803d901a413
Revises: 'ad232f3a9485'
Create Date: 2026-09-12 15:12:10.323261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a803d901a413'
down_revision: Union[str, None] = 'ad232f3a9485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_task_completion_task_date', 'task_completions', ['task_id', 'completed_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_task_completion_task_date', 'task_completions', type_='unique')
    # ### end Alembic commands ###
